on: [push, pull_request]
name: Main
jobs:
  php-cs-fixer:
    name: PHP-CS-Fixer
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: PHP-CS-Fixer
      uses: docker://oskarstark/php-cs-fixer-ga
      with:
        args: --config=.project.php_cs *
    - uses: stefanzweifel/git-auto-commit-action@v4.12.0
      with:
        commit_message: Apply php-cs-fixer changes
        branch: ${{ github.head_ref }}
